const whatsappNumber='5585994211235';
const serviceInfo={miofascial:{title:'Liberação miofascial',text:'Um protocolo para trabalhar pontos de tensão e devolver espaço ao movimento.',items:['Avaliação postural','Liberação miofascial manual','Fotobiomodulação','Eletroestimulação','Agulhamento a seco','Termoterapia','Ventosaterapia']},drenagem:{title:'Drenagem linfática',text:'Toques leves e precisos para uma experiência de desinchaço e cuidado corporal.',items:['Drenagem linfática manual','Botas pneumáticas','Termoterapia']},recovery:{title:'Recovery para você',text:'Um dia pensado para acolher seu corpo com calma, presença e um protocolo ajustado ao seu momento.',items:['Liberação miofascial de membros superiores','Botas pneumáticas','Crioterapia (piscina de gelo)']}};
const modal=document.querySelector('#service-modal');
document.querySelectorAll('[data-service]').forEach(card=>card.addEventListener('click',()=>{const d=serviceInfo[card.dataset.service];document.querySelector('#modal-title').textContent=d.title;document.querySelector('#modal-text').textContent=d.text;document.querySelector('#modal-list').innerHTML=d.items.map(i=>`<li>✦ ${i}</li>`).join('');modal.showModal();}));
document.querySelector('.modal-close').onclick=()=>modal.close();
document.querySelector('.modal-cta').addEventListener('click',()=>modal.close());
document.querySelector('.menu').addEventListener('click',()=>document.querySelector('nav').classList.toggle('open'));
document.querySelector('#booking-form').addEventListener('submit',e=>{e.preventDefault();const name=document.querySelector('#client-name').value.trim();const service=document.querySelector('#client-service').value;const message=`Olá, David! Meu nome é ${name} e tenho interesse em ${service}.`;window.open(`https://wa.me/${whatsappNumber}?text=${encodeURIComponent(message)}`,'_blank','noopener');});
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('reveal')}),{threshold:.12});document.querySelectorAll('.section,.intro-strip,.quote-section').forEach(e=>observer.observe(e));
